[kafka]
vm-kafka-1 ansible_host=192.168.122.20 ansible_user=ansible ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
vm-kafka-2 ansible_host=192.168.122.21 ansible_user=ansible ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
vm-kafka-3 ansible_host=192.168.122.22 ansible_user=ansible ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
# Для standalone оставить только один хост. Ansible сам определит режим.
#для кластера указать нужное количество хостов.